### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by roylee66** [eteam666/Auto_Build_Win_Main#1]
首次报错 修改main.py的331-343行
    else:
        config.read('Pack.ini', encoding='utf-8')
        PackName = ["Config"],["Name"]#修改过 加了逗号
        To = ["Config"],["To"]#修改过 加了逗号
        if To == "MountDir":
            To=MountDir
        if To == "Root":
            To=DOWNLOAD_PATH
        if To == "Temp":
            To=Temp
        File = To + '\\' + PackName
        patoolib.extract_archive(File, outdir=To)
        Run = ["Config"],["Run"]  #修改过 加了逗号
        CMD = f'cd {To}\\ && {Run}'
        os.system(CMD)
        logger.log(16)
        return

之后运行run继续报错

C:\Users\j\Desktop\Auto_Build_Win_Main-main>python main.py
模块存在
模块存在
模块存在
模块不存在
Requirement already satisfied: patool in c:\users\j\appdata\local\programs\python\python311\lib\site-packages (1.12)
模块存在
模块不存在
Requirement already satisfied: python-wordpress-xmlrpc in c:\users\j\appdata\local\programs\python\python311\lib\site-packages (2.3)
模块存在
Traceback (most recent call last):
  File "C:\Users\j\Desktop\Auto_Build_Win_Main-main\main.py", line 418, in <module>
    init()
  File "C:\Users\j\Desktop\Auto_Build_Win_Main-main\main.py", line 138, in init
    conn = sqlite3.connect(DataDb)
           ^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

C:\Users\j\Desktop\Auto_Build_Win_Main-main>pause
请按任意键继续. . .

**Comment by roylee66** [comment]
忘记说了 测试环境 win10 21h2 python版本3.11.1 与指定版本一致

**Comment by eteam666** [comment]
请注意，这只是部署包的配置，无需更改，只需要修改Config目录下的Config.ini即可，都有注释的，文档后续会出，有问题联系Tg @easysys2022对于数据库我会进一步查找的

**Comment by eteam666** [comment]
错误是无法连接到数据库，方便的话请Telegram私聊

**Comment by eteam666** [comment]
此版本有逻辑错误，2.18会更新，请重新获取源代码

**Comment by eteam666** [comment]
请手动添加Db文件夹，在更新时会修复此问题。因为库中没有Db文件夹，导致了无法创建文件，抱歉，若添加后还有问题，请开新的issue。感谢使用Auto Build Win
